apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:prai05/nonprod-k8s-manifests.git  
    targetRevision: develop  
    path: dev/prai/demo-app  
    
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app